title: 'MGs Wanted'
title-abbreviated: MGsWanted
description: 'Lifestyle and wellness tips for an active life'
url: 'https://www.mgs-wanted.sg'
facebook-pixel: 717923758808613
google-tag-manager: GTM-WCQ79C6
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
recommender: true
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
resources_name: articles
favicon: /images/favicon-mgswanted.ico
google_analytics: UA-160050888-1
permalink: none
baseurl: ""
defaults:
  - scope:
      path: ""
    values:
      layout: page
colors:
  primary-color: '#000000'
  secondary-color: '#ef413d'
  media-colors:
    - title: media-color-one
      color: '#fedcc4' 
    - title: media-color-two
      color: '#bedced'
    - title: media-color-three
      color: '#fedcc4'
    - title: media-color-four
      color: '#d7ebd1'
    - title: media-color-five
      color: '#d7ebd1'
staging: https://pa-mgwanted-staging.netlify.app
prod: https://pa-mgwanted-prod.netlify.app
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
