title: MGs Wanted
title-abbreviated: MGsWanted
description: >- # this means to ignore newlines until "baseurl:"
  Lifestyle and wellness tips for an active life
url: "https://www.mgs-wanted.sg" # the base hostname & protocol for your site, e.g. http://example.com
facebook-pixel: 717923758808613
google-tag-manager: GTM-WCQ79C6

# Build settings
markdown: kramdown
remote_theme: isomerpages/isomerpages-template
safe: false

plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap

# Breadcrumbs
breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

# Resource Room and Pagination
paginate: 12

# Homepage sections
homepage_hero_i_want_to: false
homepage_resources: true
homepage_careers: false

# Feedback Form URL

# FAQ URL

# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"

# Isomer recommender system - only works for simple-page, leftnav-page, and post
recommender: true

exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]

collections:
  course-directory:
    output: true
resources_name: articles